export enum DIVISION_NAME {
    DHAKA = "DHAKA",
    CHATTOGRAM = "CHATTOGRAM",
    RAJSHAHI = "RAJSHAHI",
    KHULNA = "KHULNA",
    BARISHALL = "BARISHALL",
    SYLHET = "SYLHET",
    RANGPUR = "RANGPUR",
    MYMENSINGH = "MYMENSINGH",
}